# Generated by Django 4.2.11 on 2024-08-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehiclewishlists_testing_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclewishlists',
            name='testing_field',
        ),
    ]
