# Generated by Django 4.2.11 on 2024-08-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_remove_vehiclewishlists_testing_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
