# Generated by Django 4.2.11 on 2024-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytype',
            name='vehicle_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Car'), (2, 'Bike')], null=True),
        ),
        migrations.AddField(
            model_name='colour',
            name='vehicle_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Car'), (2, 'Bike')], null=True),
        ),
        migrations.AddField(
            model_name='vehicletypenumber',
            name='vehicle_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Car'), (2, 'Bike')], null=True),
        ),
    ]
