# Generated by Django 4.2.11 on 2024-08-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_bodytype_vehicle_type_colour_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='colour',
            unique_together={('name', 'vehicle_type')},
        ),
    ]
