# Generated by Django 4.2.11 on 2024-08-20 15:28

import dj_rest_kit.helpers
import dj_rest_kit.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_bodytype_vehicle_type_alter_brand_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=dj_rest_kit.helpers.PathAndRename('vehicle-banner-image'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), dj_rest_kit.validators.image_size]),
        ),
    ]
