# Generated by Django 4.2.11 on 2024-08-01 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_protocol_address', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_protocol_address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_merchant_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Donations',
                'verbose_name_plural': 'Donations',
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_protocol_address', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_protocol_address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_merchant_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('package_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Payments',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transaction', to='package.subscription')),
            ],
            options={
                'verbose_name': 'Payment Trackers',
                'verbose_name_plural': 'Payment Trackers',
                'db_table': 'paymenttracker',
            },
        ),
    ]
