# Generated by Django 4.2.11 on 2024-08-16 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_cover_image_user_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=8)),
                ('product_type', models.IntegerField(choices=[(1, 'Vehicle Sell'), (2, 'Vehicle Rent'), (3, 'Bike Sell'), (4, 'Bike Rent'), (5, 'Garage Rent'), (6, 'Components Sell')], default=1)),
                ('product_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_review', to=settings.AUTH_USER_MODEL)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
