# Generated by Django 4.2.11 on 2024-08-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('features', '0002_alter_multimediafeature_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[(1, 'Single garage'), (2, 'Underground parking'), (3, 'Double garage'), (4, 'Open slot'), (5, 'Covered slot')], max_length=50)),
                ('garage_condition', models.TextField(blank=True, null=True)),
                ('monthly_rent_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('postal_code', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.PositiveIntegerField()),
                ('additional_field', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2, max_length=10)),
                ('rejection_message', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('optional_features', models.ManyToManyField(to='features.optionalfeature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard_features', models.ManyToManyField(to='features.standardfeature')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
            options={
                'verbose_name': 'GarageRental',
                'verbose_name_plural': 'GarageRental',
            },
        ),
        migrations.CreateModel(
            name='RentaGarageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rentagarage/')),
                ('renta_garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentagarage.garagerental')),
            ],
        ),
    ]
