# Generated by Django 4.2.11 on 2024-08-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentagarage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garagerental',
            old_name='owner',
            new_name='user',
        ),
    ]
