# Generated by Django 4.2.11 on 2024-08-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentagarage', '0002_rename_owner_garagerental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagerental',
            name='order_number',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='rentagarageimage',
            name='renta_garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentagarage_images', to='rentagarage.garagerental'),
        ),
    ]
