# Generated by Django 4.2.11 on 2024-08-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentagarage', '0003_alter_rentagarageimage_renta_garage'),
        ('rentagarage', '0003_garagerental_order_number_and_more'),
    ]

    operations = [
    ]
