# Generated by Django 4.2.11 on 2024-08-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentagarage', '0004_merge_20240828_0916'),
        ('rentagarage', '0004_merge_20240828_1708'),
    ]

    operations = [
    ]
