# Generated by Django 4.2.11 on 2024-08-01 07:08

import dj_rest_kit.helpers
import dj_rest_kit.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2)),
            ],
            options={
                'verbose_name': 'Advertisements',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisements',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dj_rest_kit.helpers.PathAndRename('advertisement-images'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), dj_rest_kit.validators.image_size])),
            ],
            options={
                'verbose_name': 'Advertisement Images',
                'verbose_name_plural': 'Advertisement Images',
                'db_table': 'advertisement_images',
            },
        ),
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('package_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('validity', models.IntegerField(default=0, help_text='In days')),
                ('number_of_vehicle', models.IntegerField(default=0)),
                ('number_of_image', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status_change_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Private'), (3, 'Dealer')])),
                ('package_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car')])),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.IntegerField(default=0, help_text='In days')),
                ('number_of_vehicle', models.IntegerField(default=0)),
                ('number_of_image', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Packages',
                'verbose_name_plural': 'Packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('package_category', models.IntegerField(choices=[(1, 'Default'), (2, 'Custom')], default=1)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('custom_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_package_subscriptions', to='package.custompackage')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_subscriptions', to='package.package')),
            ],
            options={
                'verbose_name': 'Subscriptions',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
