# Generated by Django 4.2.11 on 2024-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car'), (6, 'Rent a bike'), (7, 'Rent a garage')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car'), (6, 'Rent a bike'), (7, 'Rent a garage')]),
        ),
    ]
