# Generated by Django 4.2.11 on 2024-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_custompackage_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car'), (6, 'Rent a bike'), (7, 'Rent a garage'), (8, 'Component'), (9, 'Promotion-Rent a car'), (10, 'Promotion-Rent a bike'), (11, 'Promotion-Rent a garage')]),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Bike'), (3, 'Local'), (4, 'VIP'), (5, 'Rent a car'), (6, 'Rent a bike'), (7, 'Rent a garage'), (8, 'Component'), (9, 'Promotion-Rent a car'), (10, 'Promotion-Rent a bike'), (11, 'Promotion-Rent a garage')]),
        ),
    ]
