# Generated by Django 4.2.11 on 2024-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_custompackage_package_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
