# Generated by Django 4.2.11 on 2024-09-07 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0006_subscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='extra_image_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='package',
            name='is_personalized_banner_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_top_listing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_for',
            field=models.BigIntegerField(choices=[(1, 'Sell'), (2, 'Rent')], default=1),
        ),
        migrations.CreateModel(
            name='PackageBookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_bookmark', to='package.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_package_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PackageBookmark',
                'verbose_name_plural': 'PackageBookmark',
                'db_table': 'package_bookmark',
            },
        ),
    ]
