# Generated by Django 4.2.11 on 2024-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_package_extra_image_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='package_for',
            field=models.BigIntegerField(choices=[(1, 'Sell'), (2, 'Rent')], default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_personalized_banner_enabled',
            field=models.BooleanField(default=False, help_text='Enable if you want to add personalized banner image.'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_top_listing_enabled',
            field=models.BooleanField(default=False, help_text='Enable if you want to mark this package in top listing'),
        ),
    ]
