# Generated by Django 4.2.11 on 2024-08-01 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('running_mileage', models.PositiveIntegerField()),
                ('body_type', models.CharField(choices=[(1, 'SUV'), (2, 'Heavy Duty'), (3, 'BDOUBLE'), (4, 'BMX'), (5, 'BOBCAT'), (6, 'BULLD')], max_length=50)),
                ('registration_month', models.CharField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'Jun'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=20)),
                ('registration_year', models.PositiveIntegerField()),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_condition', models.CharField(choices=[(1, 'New'), (2, 'Used')], max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('daily_base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('postal_code', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[(1, 'Electricity'), (2, 'Plugin hybrid'), (3, 'Hybrid'), (4, 'Gasoline'), (5, 'Diesel')], max_length=50)),
                ('cubic_capacity', models.PositiveBigIntegerField(blank=True, null=True)),
                ('energy_efficiency', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G')], max_length=5)),
                ('horse_power', models.PositiveBigIntegerField()),
                ('luggage_capacity', models.PositiveBigIntegerField()),
                ('doors', models.PositiveBigIntegerField()),
                ('seats', models.PositiveBigIntegerField()),
                ('fuel_consumption', models.PositiveBigIntegerField()),
                ('transmission', models.CharField(choices=[(1, 'Manual'), (2, 'Automatic')], max_length=50)),
                ('retail_value', models.PositiveIntegerField()),
                ('tires', models.CharField(choices=[(1, 'All season tires'), (2, 'Winter times')], max_length=20)),
                ('comfort', models.CharField(choices=[(1, 'Air conditioning'), (2, 'Heated seats')], max_length=20)),
                ('additional_field', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2, max_length=10)),
                ('rejection_message', models.TextField(blank=True, null=True)),
                ('testing_field', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.carbrand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.carmodel')),
                ('multimedia', models.ManyToManyField(to='features.multimediafeature')),
                ('optional_features', models.ManyToManyField(to='features.optionalfeature')),
            ],
            options={
                'verbose_name': 'CarRental',
                'verbose_name_plural': 'CarRental',
            },
        ),
    ]
