# Generated by Django 4.2.11 on 2024-08-01 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentacar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrental',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrental',
            name='safety_and_assistance',
            field=models.ManyToManyField(to='features.safetyassistancefeature'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='standard_features',
            field=models.ManyToManyField(to='features.standardfeature'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='rentacar.carbrand', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentacar.carrental'),
        ),
    ]
