# Generated by Django 4.2.11 on 2024-08-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='testing_field',
        ),
    ]
