# Generated by Django 4.2.11 on 2024-08-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0007_carrental_brand_carrental_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='testing_field',
        ),
        migrations.AddField(
            model_name='carrental',
            name='order_number',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
