# Generated by Django 4.2.11 on 2024-08-22 17:43

import dj_rest_kit.helpers
import dj_rest_kit.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0013_vehicle_banner'),
        ('package', '0003_alter_custompackage_package_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('vehicle_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Bike')], default=1)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=dj_rest_kit.helpers.PathAndRename('component-banner-image'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), dj_rest_kit.validators.image_size])),
                ('name', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('component_conditions', models.IntegerField(choices=[(1, 'New'), (2, 'Used')], default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery', models.IntegerField(choices=[(1, 'Home Delivery'), (2, 'Take Away')], default=1)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=1)),
                ('warranty', models.IntegerField(choices=[(1, 'From date'), (2, 'From registration date'), (3, 'From takeover'), (4, 'From guarantee')], default=1)),
                ('additional_guarantee_text', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('additional_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Components',
                'verbose_name_plural': 'Components',
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Component Categories',
                'verbose_name_plural': 'Component Categories',
                'db_table': 'component_category',
            },
        ),
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dj_rest_kit.helpers.PathAndRename('component-images'), validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), dj_rest_kit.validators.image_size])),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_images', to='component.component')),
            ],
            options={
                'verbose_name': 'Component Images',
                'verbose_name_plural': 'Component Images',
                'db_table': 'component_images',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.componentcategory'),
        ),
        migrations.AddField(
            model_name='component',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.brand'),
        ),
        migrations.AddField(
            model_name='component',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.subscription'),
        ),
    ]
