# Generated by Django 4.2.11 on 2024-08-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_custompackage_package_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='component',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_subscription', to='package.subscription'),
        ),
    ]
