# Generated by Django 4.2.11 on 2024-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_component_user_alter_component_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='activation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.IntegerField(choices=[(2, 'Pending'), (0, 'Rejected'), (1, 'Approved')], default=2),
        ),
    ]
