# Generated by Django 4.2.11 on 2024-09-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('component', '0003_component_activation_date_component_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentWishlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_component', to='component.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_component_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Component Wishlist',
                'verbose_name_plural': 'Component Wishlist',
                'db_table': 'component_wishlist',
            },
        ),
    ]
