# Generated by Django 4.2.11 on 2024-08-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0012_alter_bodytype_vehicle_type_alter_brand_vehicle_type_and_more'),
        ('features', '0002_alter_multimediafeature_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('running_mileage', models.PositiveIntegerField()),
                ('body_type', models.CharField(blank=True, choices=[(1, 'SUV'), (2, 'Heavy Duty'), (3, 'BDOUBLE'), (4, 'BMX'), (5, 'BOBCAT'), (6, 'BULLD')], max_length=50, null=True)),
                ('registration_month', models.CharField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'Jun'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=20, null=True)),
                ('registration_year', models.PositiveIntegerField()),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_condition', models.CharField(blank=True, choices=[(1, 'New'), (2, 'Used')], max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, choices=[(1, 'Manual'), (2, 'Automatic')], max_length=50, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('daily_base_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('postal_code', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=200)),
                ('street_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(blank=True, choices=[(1, 'Electricity'), (2, 'Plugin hybrid'), (3, 'Hybrid'), (4, 'Gasoline'), (5, 'Diesel')], max_length=50, null=True)),
                ('energy_efficiency', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G')], max_length=5)),
                ('horse_power', models.PositiveBigIntegerField()),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('additional_field', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Accepted'), (0, 'Rejected'), (2, 'Pending')], default=2, max_length=10)),
                ('rejection_message', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.brand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.model')),
                ('multimedia', models.ManyToManyField(to='features.multimediafeature')),
                ('optional_features', models.ManyToManyField(to='features.optionalfeature')),
                ('safety_and_assistance', models.ManyToManyField(to='features.safetyassistancefeature')),
                ('standard_features', models.ManyToManyField(to='features.standardfeature')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BikeRental',
                'verbose_name_plural': 'BikeRental',
            },
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='rentabike.bikerental')),
            ],
        ),
    ]
