# Generated by Django 4.2.11 on 2024-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='order_number',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
