# Generated by Django 4.2.11 on 2024-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentabike', '0002_bikerental_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerental',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikerental',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
